[package]
name = "secmem-alloc"
version = "0.1.0"
authors = ["niluxv <niluxv.opensource.C-h2ty6xl@yandex.com>"]
edition = "2018"
build = "build.rs"
license = "MIT OR Apache-2.0"
description = "Custom allocators for secret memory"
readme = "README.md"
categories = ["no-std", "memory-management", "cryptography"]
keywords = ["allocator", "secure", "memory"]
repository = "https://github.com/niluxv/secmem-alloc"

[package.metadata.docs.rs]
all-features = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std", "cc"]
std = ["thiserror"]
nightly_allocator_api = []
nightly_core_intrinsics = []
nightly = ["nightly_allocator_api", "nightly_core_intrinsics"]
# required features to run tests; additional features enable more tests
dev = ["std", "nightly_allocator_api"]

[dependencies]
cfg-if = "1.0"
libc = "0.2"
thiserror = {version = "1.0", optional = true}

[dev-dependencies]
criterion = "0.3"

[build-dependencies]
cc = {version = "^1.0", optional = true}

[[bench]]
name = "bench_zeroizers"
harness = false
