name: Check

on: [push, pull_request]

jobs:
  check_stable:
    name: Check Stable
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo check
        uses: clechasseur/rs-cargo@v2
        with:
          command: check

  test_nightly_devfeatures:
    name: Test Suite (Nightly) Dev Features
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run cargo test
        uses: clechasseur/rs-cargo@v2
        with:
          command: test
          args: --no-default-features --features dev

  test_nightly_allfeatures:
    name: Test Suite (Nightly) All Features
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run cargo test
        uses: clechasseur/rs-cargo@v2
        with:
          command: test
          args: --all-features
        env:
          RUSTFLAGS: "-Ctarget-cpu=native"

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Run cargo doc
        uses: clechasseur/rs-cargo@v2
        with:
          command: doc
          args: --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Run cargo fmt
        uses: clechasseur/rs-cargo@v2
        with:
          command: fmt
          args: -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
            components: clippy

      - uses: clechasseur/rs-cargo@v2
        with:
          command: clippy
          args: --all-features

  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Get latest toolchain version with miri
        run: echo "TOOLCHAIN=$(curl -s https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu/miri)" >> $GITHUB_ENV

      - name: Install latest nightly toolchain with miri
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-${{ env.TOOLCHAIN }}
          components: rust-src, miri

      - name: Run cargo miri test
        run: cargo miri test --all-features
        env:
          MIRI_LOG: 1
          MIRI_BACKTRACE: 1
          MIRIFLAGS: -Zmiri-strict-provenance
